### ISSUE TITLE
[2.5.2] SDO Transfer device property is not always initialized

### ISSUE THREAD

**Issue by bdcdekimo** [Daxbot/node-canopen#20]
When a client tries to initiate an upload or download of an entry that does not exist, `device.receive()` throws a TypeError.

Example stack trace for an upload:

```
TypeError: Cannot read property 'send' of undefined
    at Transfer.send (/appfs/apps/nodejs-server/node_modules/canopen/src/protocol/sdo.js:221:21)
    at Transfer.abort (/appfs/apps/nodejs-server/node_modules/canopen/src/protocol/sdo.js:260:14)
    at Sdo._serverUploadInitiate (/appfs/apps/nodejs-server/node_modules/canopen/src/protocol/sdo.js:796:27)
    at Sdo._onMessage (/appfs/apps/nodejs-server/node_modules/canopen/src/protocol/sdo.js:987:26)
    at emitOne (events.js:121:20)
    at Device.emit (events.js:211:7)
    at Device.receive (/appfs/apps/nodejs-server/node_modules/canopen/src/device.js:104:18)
```

It looks like `this.device` of the `Transfer` objects in the `Sdo`'s `this.clients` are not initialized anywhere and that's why the send() function throws.
I'm only using the library to implement an SDO server, but it looks like the SDO client implementation does not have this problem: `this.device` of the `Transfer` objects in the `Sdo`'s `this.transfers` is initialized correctly, it seems.

**Comment by wilkinsw** [comment]
Should be resolved in [2.5.3-beta](https://www.npmjs.com/package/canopen/v/2.5.3-beta)
